apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: prefect
data:
  POSTGRES_DB: <POSTGRES_DB>
  POSTGRES_USER: <POSTGRES_USER>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prefect
type: Opaque
data:
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD_BASE_64>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: prefect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: prefect
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
